name: sequentiality
channels:
  - conda-forge
  - defaults
dependencies:
  - zlib==1.2.13
  - xz==5.4.6
  - wheel==0.44.0
  - tk==8.6.14
  - sqlite==3.45.3
  - setuptools==75.1.0
  - readline==8.2
  - python==3.12.7
  - openssl==3.0.15
  - ncurses==6.4
  - libffi==3.4.4
  - libcxx==14.0.6
  - expat==2.6.3
  - ca-certificates==2024.9.24
  - bzip2==1.0.8
  - pip
  - transformers  # Add the missing transformers package
  - sentencepiece # Transformers dependencies often include this
  - cudatoolkit=11.3  # Ensure GPU compatibility if needed
  - cudnn=8.2
  - pip:
      - requirements.txt  # Make sure you have this file and install via pip for specific dependencies
