#!/bin/bash

#SBATCH --job-name=test       ## Name of the job.
#SBATCH -A bornstea_lab_gpu   ## CHANGE account to charge
#SBATCH -p gpu                ## specify free-gpu partition
#SBATCH --nodes=1             ## (-N) number of nodes to use
#SBATCH --ntasks=1            ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=1     ## number of cores the job needs
#SBATCH --error=slurm-%J.err  ## error log file
#SBATCH --output=slurm-%J.out ## output log file
#SBATCH --mail-type=end
#SBATCH --mail-user=agoesche@uci.edu
#SBATCH --gres=gpu:A100:1     # specify 1 GPU of type A100
#SBATCH --array=1-9           # Run 9 jobs with array indices 1-9

# Run command hostname and save output to the file out.txt
source ~/.bashrc

conda activate practice

# SLURM_ARRAY_TASK_ID will be 1, 2, 3, ... 9
python3 main.py ${SLURM_ARRAY_TASK_ID}

exit