from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import numpy as np
from src.keys import HUGGING_FACE_TOKEN
import re

if torch.backends.mps.is_built():  # Apple Silicon
    print('mps is used.')
    mps_device = torch.device("mps")
elif torch.backends.cuda.is_built():  # Real GPU
    print('cuda is used.')
    mps_device = torch.device("cuda")
else:  # If all else fails
    print('cpu is used.')
    mps_device = torch.device("cpu")

torch.set_default_dtype(torch.float64)  # Use double precision

class SequentialityModel:
    def __init__(self, model_name : str, topic : str, recall_length=4) -> None:
        self.sentences = []

        self.recall_length = recall_length

        self.tokenizer = AutoTokenizer.from_pretrained(model_name,
                                                       token=HUGGING_FACE_TOKEN,
                                                       use_safetensors=True,
                                                       padding_side="left")
        self.model = AutoModelForCausalLM.from_pretrained(model_name,
                                                          token=HUGGING_FACE_TOKEN,
                                                          torch_dtype=torch.bfloat16,
                                                          device_map=mps_device,
                                                          use_safetensors=True).to(mps_device)

        self.model.config.pad_token_id = self.model.config.eos_token_id

        # turn off gradient descent
        torch.set_grad_enabled(False)

        # Pad all text with _
        self.context_string = f"_condition every word on this topic: <TOPIC>{topic}<END_TOPIC> "

    def _to_tokens_and_logprobs(self, text: str) -> list[list[tuple[int, float]]]:
        input_text = self.context_string + text

        input_ids = self.tokenizer(input_text, padding=True, return_tensors="pt").input_ids.to(mps_device)
        outputs = self.model(input_ids)
        probs = torch.log_softmax(outputs.logits, dim=-1).detach()

        # collect the probability of the generated token -- probability at index 0 corresponds to the token at index 1
        probs = probs[:, :-1, :]
        input_ids = input_ids[:, 1:]
        gen_probs = torch.gather(probs, 2, input_ids[:, :, None]).squeeze(-1)

        batch = []
        for input_sentence, input_probs in zip(input_ids, gen_probs):
            token_sequence = []
            for token, p in zip(input_sentence, input_probs):
                if token.item() not in self.tokenizer.all_special_ids:
                    token_sequence.append((token.item(), p.item()))
            batch.append(token_sequence)
        return batch


    @staticmethod
    def _process_tokens_and_logprobs(query_token_ids: list[int], tokens_and_logprobs: list[(str, float)]) -> float:
        """
        Function that returns the sum of logprobs of the tokens in query sentence - basically finds a continuous subset

        :param query_tokens: list of tokens generated from input text - only one sentence
        :param tokens_and_logprobs: list of tuples of tokens and their log-probabilities had they been generated by the LLM

        :return: sum of log-probabilities of just the sentence represented by `query_tokens`
        :rtype: float
        """
        i = 0
        while i < len(tokens_and_logprobs):
            if tokens_and_logprobs[i][0] == query_token_ids[0]:
                for j in range(len(query_token_ids)):
                    # Ensure you don't go out of bounds
                    if i + j >= len(tokens_and_logprobs) or tokens_and_logprobs[i + j][0] != query_token_ids[j]:
                        i += j  # skip these many tokens and break out to try again
                        break
                else:
                    # If the loop completes without a break, we've found a match
                    return sum(p for _, p in tokens_and_logprobs[i:i+len(query_token_ids)])
            i += 1

        return 0

    def _calculate_contextual_sequentiality(self, sentence : str, sentence_tokens : list[str], i : int,  h : int, verbose : bool = False) -> float:
        """
        Calculate the contextually dependent sequentiality of a sentence.

        :param sentence: raw input sentence
        :param sentence_tokens: tokenized version of sentence
        :param i: index of current sentence
        :param h: number of sentences to use for context

        :return: contextual sequentiality value - Log(P(sentence | previous h sentences ^ topic))
        :rtype: float
        """
        raw_sequentiality = 0
        if i - h < 0:
            context = ". ".join(self.sentences[:i])

        else:
            context = ". ".join(self.sentences[i - h:i])

        if len(context) == 0:  # beginning of the text - prevents random period at the front of the text
            input_text = sentence + "."
        else:
            input_text = context + ". " + sentence + "."

        tokens_and_logprobs = self._to_tokens_and_logprobs(input_text)[0]

        return self._process_tokens_and_logprobs(sentence_tokens, tokens_and_logprobs)

    def _calculate_topic_sequentiality(self, sentence : str, sentence_tokens : list[str], verbose : bool = False) -> float:
        """
        Calculate the sequentiality of a sentence given only a topic

        :param sentence: raw input sentence,
        :param sentence_tokens: tokenized version of sentence

        :return: topic sequentiality value - Log(P(sentence | topic))
        :rtype: float
        """
        tokens_and_logprobs = self._to_tokens_and_logprobs(sentence + ".")[0]

        return self._process_tokens_and_logprobs(sentence_tokens, tokens_and_logprobs)

    def _calculate_sentence_sequentiality(self, sentence : str, i: int, verbose : bool = False) -> [float]:
        """

        Calculates the sequentiality of a given sentence by subtracting the context dependent sequentiality from
        the purely topic driven version.

        :param sentence: raw input sentence
        :param i: index of current sentence
        :param verbose: debug

        :return: [total_sentence_sequentiality, contextual_sequentiality, topic_sequentiality]
        :rtype: list[float]
        """
        sentence_token_ids = self.tokenizer.encode(sentence + ".")
    
        topic_sequentiality = self._calculate_topic_sequentiality(sentence, sentence_token_ids)
        contextual_sequentiality = self._calculate_contextual_sequentiality(
            sentence=sentence,
            sentence_tokens=sentence_token_ids,
            i=i,
            h=self.recall_length,
            verbose=False
        )

        if verbose:
            print(f"topic sequentiality: {topic_sequentiality}\ncontext sequentiality: {contextual_sequentiality}\nsentence token IDs: {sentence_token_ids}")
        # Normalize by the number of tokens (note: if needed, adjust this)
        return [(topic_sequentiality - contextual_sequentiality) / -len(sentence_token_ids), contextual_sequentiality, topic_sequentiality]

    def calculate_text_sequentiality(self, text : str, verbose : bool = False) -> list[float | list]:
        """
        Function that calculates the total sequentiality of a text

        :param text: entire input text
        :param verbose: debug

        :return: [total_text_sequentiality, total_sentence-level_sequentiality, contextual_sentence-level_sequentiality, topic_sentence-level_sequentiality]
        :rtype: list[float | list]
        """
        self.sentences = re.split('[\.\?\!]\s*', text)
        total_sequentialities = []
        contextual_sequentialities = []
        topic_sequentialities = []

        for i, sentence in enumerate(self.sentences):
            if sentence == "": continue

            total, contextual, topic = self._calculate_sentence_sequentiality(sentence, i, verbose)
            total_sequentialities.append(total)
            contextual_sequentialities.append(contextual)
            topic_sequentialities.append(topic)

        return [np.mean(total_sequentialities), total_sequentialities, contextual_sequentialities, topic_sequentialities]


if __name__ == "__main__":
    model = SequentialityModel("microsoft/Phi-3-mini-4k-instruct", topic="a conversation with a doctor")
    # model = SequentialityModel("meta-llama/Llama-3.3-70B-Instruct", topic="a conversation with a doctor")
    print(f"\nshould be lower  : {model.calculate_text_sequentiality("There are two bison standing next to each other. They seem to be friends. Why is this not working.", False)}")
    print(f"\nshould be higher : {model.calculate_text_sequentiality("I broke my arm. It hurts a lot, and I don't know if it'll ever heal. When I looked down, I could see the bone sticking out.", False)}")

